"""Offline regression for TecDoc/reference and SAP worklist parsing."""

import sys
import tempfile
from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.styles import PatternFill

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))

from hs_reference import (
    HsReference,
    normalize_code,
    normalize_product,
    normalize_tecdoc,
)
from hs_worklist import (
    analyze,
    build_description_plan,
    read_worklist,
    save_remaining_worklist,
    selected_groups,
)


def save_book(path: Path, rows: list[list]) -> None:
    wb = Workbook()
    ws = wb.active
    for row in rows:
        ws.append(row)
    wb.save(path)
    wb.close()


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="hs-data-") as tmp:
        tmp_path = Path(tmp)
        reference_path = tmp_path / "reference.xlsx"
        worklist_path = tmp_path / "worklist.xlsx"

        # Real files often contain title rows, inconsistent casing/spacing and
        # duplicate TecDoc rows with complementary values.
        save_book(
            reference_path,
            [
                ["Classification reference generated by TecDoc"],
                [],
                [
                    " tecdoc ",
                    "TECDOC   text",
                    "eu   taric",
                    "CHINA",
                    None,
                    None,
                    None,
                    None,
                    None,
                    "German Description",
                    "English Description",
                ],
                [
                    1001,
                    "Sensor",
                    None,
                    "85365000",
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Sensor DE",
                    None,
                ],
                [
                    "1001.0",
                    None,
                    "90.32.8900",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Sensor EN",
                ],
                [
                    1002.0,
                    "Control unit",
                    "90328900",
                    "85371090",
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Control DE",
                    "Control EN",
                ],
            ],
        )
        reference = HsReference(reference_path)
        assert reference.header_row == 3
        assert reference.tecdoc_count == 2
        assert reference.has_column("EU TARIC")
        assert reference.code_for("1001", "EU TARIC") == "90328900"
        assert reference.describe("1001") == "Sensor"
        assert reference.value_for("1001", "J") == "Sensor DE"
        assert reference.value_for("1001", "English Description") == "Sensor EN"

        # The status column deliberately precedes Product Number. Prefix-based
        # matching must not mistake it for the material identifier.
        save_book(
            worklist_path,
            [
                ["SAP GTS export"],
                ["generated", "offline"],
                [
                    "Product Classification Status",
                    "Product Number",
                    "Generic Article Number (TECDOC)",
                    "Product Short Text",
                    "Material Type",
                    "Country/Country Group",
                ],
                ["Not classified", 355135851.0, 1001.0, "Sensor A", "FERT", "EU"],
                ["Not classified", "355136431", "1002", "Control B", "FERT", "GB"],
                ["Not classified", "355136441", None, "Missing TecDoc", "FERT", "EU"],
                ["Not classified", "355136450", None, "Duplicate empty", "FERT", ""],
                [
                    "Not classified",
                    "355136450",
                    "1002",
                    "Duplicate valid",
                    "FERT",
                    "EU",
                ],
                ["Not classified", "355136460", "1001", "Conflict A", "FERT", "EU GB"],
                ["Not classified", "355136460", "1002", "Conflict B", "FERT", "EU"],
            ],
        )
        worklist = read_worklist(worklist_path)
        assert [row["product"] for row in worklist] == [
            "355135851",
            "355136431",
            "355136441",
            "355136450",
            "355136450",
            "355136460",
            "355136460",
        ]
        result = analyze(worklist, reference, "EDCHSCDEEX")
        assert result["summary"]["ready"] == 3, result["summary"]
        assert result["summary"]["blocked"] == 2, result["summary"]
        assert len(result["groups"]) == 1, result["groups"]
        assert result["groups"][0]["hs_code"] == "90328900"
        assert result["groups"][0]["count"] == 3
        assert {item["reason"] for item in result["blocked"]} == {
            "missing_tecdoc",
            "conflicting_tecdoc",
        }
        assert selected_groups(result, []) == []
        assert len(selected_groups(result, None)) == 1

        # The per-scheme remaining file must preserve the SAP workbook and
        # remove every row for products explicitly confirmed as maintained.
        exact_source = tmp_path / "sap-original.xlsx"
        exact_target = tmp_path / "remaining.xlsx"
        wb = Workbook()
        ws = wb.active
        ws.title = "Worklist"
        ws.append(["SAP GTS worklist export"])
        ws.append(["generated", "offline"])
        ws.append(
            [
                "Product Classification Status",
                "Product Number",
                "Generic Article Number (TECDOC)",
                "Product Short Text",
            ]
        )
        ws["B3"].fill = PatternFill("solid", fgColor="1F4E78")
        ws.column_dimensions["B"].width = 24
        ws.append(["Not classified", "100", "10", "Remove A"])
        ws.append(["Not classified", "200", "20", "Keep"])
        ws.append(["Not classified", "100", "10", "Remove duplicate"])
        ws.append(["Not classified", "300", "30", "Keep too"])
        notes = wb.create_sheet("Export metadata")
        notes["A1"] = "must stay unchanged"
        wb.save(exact_source)
        wb.close()

        remaining_stats = save_remaining_worklist(
            exact_source,
            exact_target,
            {"100", "999"},
        )
        assert remaining_stats["requested_products"] == 2
        assert remaining_stats["removed_products"] == 1
        assert remaining_stats["removed_rows"] == 2
        assert remaining_stats["remaining_products"] == 2
        assert remaining_stats["unmatched_products"] == ["999"]
        preserved = load_workbook(exact_target, data_only=False)
        try:
            assert preserved.sheetnames == ["Worklist", "Export metadata"]
            remaining_ws = preserved["Worklist"]
            assert remaining_ws["A1"].value == "SAP GTS worklist export"
            assert remaining_ws["B3"].fill.fgColor.rgb.endswith("1F4E78")
            assert remaining_ws.column_dimensions["B"].width == 24
            assert [remaining_ws.cell(row, 2).value for row in range(4, 6)] == [
                "200",
                "300",
            ]
            assert preserved["Export metadata"]["A1"].value == "must stay unchanged"
        finally:
            preserved.close()

        description_languages = [
            {"code": "DE", "column": "J", "country_name": "Germany"},
            {
                "code": "EN",
                "column": "K",
                "country_name": "United Kingdom",
            },
        ]
        plan = build_description_plan(
            result["groups"], reference, description_languages
        )
        assert plan["summary"] == {
            "products": 3,
            "ready": 3,
            "missing": 0,
            "skipped": 0,
        }
        by_product = {item["product"]: item for item in plan["items"]}
        assert by_product["355135851"]["languages"] == ["DE"]
        assert by_product["355135851"]["descriptions"] == {"DE": "Sensor DE"}
        assert by_product["355136431"]["languages"] == ["EN"]
        assert by_product["355136431"]["descriptions"] == {"EN": "Control EN"}
        assert by_product["355136450"]["country_groups"] == ["EU"]

        missing_reference_path = tmp_path / "missing-description.xlsx"
        save_book(
            missing_reference_path,
            [
                [
                    "TECDOC",
                    "Text",
                    "EU TARIC",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "DE",
                    "EN",
                ],
                [
                    1001,
                    "Sensor",
                    "90328900",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Sensor DE",
                    None,
                ],
            ],
        )
        missing_reference = HsReference(missing_reference_path)
        missing_plan = build_description_plan(
            [
                {
                    "products": [
                        {
                            "product": "355135851",
                            "tecdoc": "1001",
                            "country": "GB",
                        }
                    ]
                }
            ],
            missing_reference,
            description_languages,
        )
        assert missing_plan["summary"]["missing"] == 1
        assert missing_plan["missing"][0]["missing_languages"] == ["EN"]

        eu_only_plan = build_description_plan(
            [
                {
                    "products": [
                        {
                            "product": "355135851",
                            "tecdoc": "1001",
                            "country": "EU",
                        }
                    ]
                }
            ],
            missing_reference,
            description_languages,
        )
        assert eu_only_plan["summary"]["missing"] == 0
        assert eu_only_plan["items"][0]["languages"] == ["DE"]

        skipped_plan = build_description_plan(
            [
                {
                    "products": [
                        {
                            "product": "355135851",
                            "tecdoc": "1001",
                            "country": "US",
                        }
                    ]
                }
            ],
            missing_reference,
            description_languages,
        )
        assert skipped_plan["summary"] == {
            "products": 1,
            "ready": 0,
            "missing": 0,
            "skipped": 1,
        }

        conflict_path = tmp_path / "conflict.xlsx"
        save_book(
            conflict_path,
            [
                ["TECDOC", "EU TARIC"],
                [1001, "90328900"],
                [1001, "90329000"],
            ],
        )
        try:
            HsReference(conflict_path)
        except ValueError as exc:
            assert "conflictuale" in str(exc), exc
        else:
            raise AssertionError("Conflicting duplicate TecDoc was silently accepted")

        description_conflict_path = tmp_path / "description-conflict.xlsx"
        save_book(
            description_conflict_path,
            [
                [
                    "TECDOC",
                    "EU TARIC",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "DE",
                    "EN",
                ],
                [
                    1001,
                    "90328900",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Text A",
                    "Text EN",
                ],
                [
                    1001,
                    "90328900",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "Text B",
                    "Text EN",
                ],
            ],
        )
        description_conflict = HsReference(description_conflict_path)
        try:
            description_conflict.value_for("1001", "J")
        except ValueError as exc:
            assert "conflictuale" in str(exc), exc
        else:
            raise AssertionError("Conflicting duplicate description was accepted")

    assert normalize_tecdoc("1.002E+3") == "1002"
    assert normalize_tecdoc("N/A") == ""
    assert normalize_product(355135851.0) == "355135851"
    assert normalize_code("90.32 89-00") == "90328900"
    assert normalize_code("#N/A") == ""
    print("PASS TecDoc/reference/worklist normalization and conflict guard")
    print("RESULT= PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
